sonar.organization=mzworthington
sonar.projectKey=mzworthington_RoMini
sonar.exclusions=.github/workflows/**
sonar.test.inclusions=**/test_*.py
sonar.coverage.exclusions=**/test_*.py
sonar.python.coverage.reportPaths=coverage.xml
